apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    app: nginx-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
      version: blue
  template:
    metadata:
      labels:
        app: nginx-app
        version: blue
    spec:
      containers:
      - name: nginx
        image: 19980617/harness:9phxvQsXQmiBdO2fdSAUHQ  # Change to your actual Blue image
        ports:
        - containerPort: 80
