apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  labels:
    app: nginx-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
      version: green
  template:
    metadata:
      labels:
        app: nginx-app
        version: green
    spec:
      containers:
      - name: nginx
        image: 19980617/harness:o-OVdAU4SSaQqDNISlTRgw  # Change to your actual Green image
        ports:
        - containerPort: 80
