apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  labels:
    app: nginx
    version: green
    harness.io/color: green  # Added this label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: green
      harness.io/color: green  # Ensure selector matches labels in template
  template:
    metadata:
      labels:
        app: nginx
        version: green
        harness.io/color: green  # Added this label
    spec:
      containers:
      - name: nginx
        image: 19980617/harness:o-OVdAU4SSaQqDNISlTRgw
        ports:
        - containerPort: 80
