# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   labels:
#     app: nginx-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nginx-app
#   template:
#     metadata:
#       labels:
#         app: nginx-app
#     spec:
#       containers:
#       - name: nginx
#         image: 19980617/harness:9phxvQsXQmiBdO2fdSAUHQ
#         ports:
#         - containerPort: 80

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: LoadBalancer  # Exposing NGINX via LoadBalancer
#   selector:
#     app: nginx-app
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stable
  annotations:
    harness.io/direct-apply: "true"  # Tells Harness to apply this directly, not as part of canary
  labels:
    app: nginx-app
    version: stable
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: nginx-app
      version: stable
  template:
    metadata:
      labels:
        app: nginx-app
        version: stable
    spec:
      containers:
      - name: nginx
        image: 19980617/harness:o-OVdAU4SSaQqDNISlTRgw
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary
  labels:
    app: nginx-app
    version: canary
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: nginx-app
      version: canary
  template:
    metadata:
      labels:
        app: nginx-app
        version: canary
    spec:
      containers:
      - name: nginx
        image: 19980617/harness:9phxvQsXQmiBdO2fdSAUHQ
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-app  
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
